#CI项目名
name: Delete-tag-and-release

on:
  #自动执行：每周六早上0点
  schedule:
    - cron: 0 15 * * Sat
  #手动编译
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
#CI权限
permissions: write-all

#CI任务
jobs:
  del_core:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 0
        delete_tags: true
    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0